steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function_cicd
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --allow-unauthenticated
  - --service-account=gcp-devops-433010@appspot.gserviceaccount.com
options:
  logging : CLOUD_LOGGING_ONLY
